default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /tmp/mysql.sock
  # 接続先を別コンテナのdbに設定
  host: db
  # MySQLのrootユーザーを使用
  username: root
  # コンテナ内の環境変数を展開した値をpasswordに設定
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] %>

development:
  <<: *default
  database: othello_app_development
